// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelData is an autogenerated mock type for the ModelData type
type ModelData struct {
	mock.Mock
}

type ModelData_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelData) EXPECT() *ModelData_Expecter {
	return &ModelData_Expecter{mock: &_m.Mock}
}

// NewModelData creates a new instance of ModelData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelData(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelData {
	mock := &ModelData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
