// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	lineblocs "github.com/Lineblocs/go-helpers"
	mock "github.com/stretchr/testify/mock"

	model "lineblocs.com/api/model"

	sql "database/sql"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CaptureSIPMessage provides a mock function with given fields: _a0, _a1
func (_m *Store) CaptureSIPMessage(_a0 string, _a1 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CaptureSIPMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureSIPMessage'
type Store_CaptureSIPMessage_Call struct {
	*mock.Call
}

// CaptureSIPMessage is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) CaptureSIPMessage(_a0 interface{}, _a1 interface{}) *Store_CaptureSIPMessage_Call {
	return &Store_CaptureSIPMessage_Call{Call: _e.mock.On("CaptureSIPMessage", _a0, _a1)}
}

func (_c *Store_CaptureSIPMessage_Call) Run(run func(_a0 string, _a1 string)) *Store_CaptureSIPMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_CaptureSIPMessage_Call) Return(_a0 []byte, _a1 error) *Store_CaptureSIPMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CaptureSIPMessage_Call) RunAndReturn(run func(string, string) ([]byte, error)) *Store_CaptureSIPMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CheckBYOPSTNIPWhitelist provides a mock function with given fields: _a0, _a1
func (_m *Store) CheckBYOPSTNIPWhitelist(_a0 string, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CheckBYOPSTNIPWhitelist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBYOPSTNIPWhitelist'
type Store_CheckBYOPSTNIPWhitelist_Call struct {
	*mock.Call
}

// CheckBYOPSTNIPWhitelist is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) CheckBYOPSTNIPWhitelist(_a0 interface{}, _a1 interface{}) *Store_CheckBYOPSTNIPWhitelist_Call {
	return &Store_CheckBYOPSTNIPWhitelist_Call{Call: _e.mock.On("CheckBYOPSTNIPWhitelist", _a0, _a1)}
}

func (_c *Store_CheckBYOPSTNIPWhitelist_Call) Run(run func(_a0 string, _a1 string)) *Store_CheckBYOPSTNIPWhitelist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_CheckBYOPSTNIPWhitelist_Call) Return(_a0 bool, _a1 error) *Store_CheckBYOPSTNIPWhitelist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CheckBYOPSTNIPWhitelist_Call) RunAndReturn(run func(string, string) (bool, error)) *Store_CheckBYOPSTNIPWhitelist_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPSTNIPWhitelist provides a mock function with given fields: _a0, _a1
func (_m *Store) CheckPSTNIPWhitelist(_a0 string, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CheckPSTNIPWhitelist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPSTNIPWhitelist'
type Store_CheckPSTNIPWhitelist_Call struct {
	*mock.Call
}

// CheckPSTNIPWhitelist is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) CheckPSTNIPWhitelist(_a0 interface{}, _a1 interface{}) *Store_CheckPSTNIPWhitelist_Call {
	return &Store_CheckPSTNIPWhitelist_Call{Call: _e.mock.On("CheckPSTNIPWhitelist", _a0, _a1)}
}

func (_c *Store_CheckPSTNIPWhitelist_Call) Run(run func(_a0 string, _a1 string)) *Store_CheckPSTNIPWhitelist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_CheckPSTNIPWhitelist_Call) Return(_a0 bool, _a1 error) *Store_CheckPSTNIPWhitelist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CheckPSTNIPWhitelist_Call) RunAndReturn(run func(string, string) (bool, error)) *Store_CheckPSTNIPWhitelist_Call {
	_c.Call.Return(run)
	return _c
}

// DoVerifyCaller provides a mock function with given fields: _a0, _a1
func (_m *Store) DoVerifyCaller(_a0 *model.Workspace, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Workspace, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*model.Workspace, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*model.Workspace, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_DoVerifyCaller_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoVerifyCaller'
type Store_DoVerifyCaller_Call struct {
	*mock.Call
}

// DoVerifyCaller is a helper method to define mock.On call
//   - _a0 *model.Workspace
//   - _a1 string
func (_e *Store_Expecter) DoVerifyCaller(_a0 interface{}, _a1 interface{}) *Store_DoVerifyCaller_Call {
	return &Store_DoVerifyCaller_Call{Call: _e.mock.On("DoVerifyCaller", _a0, _a1)}
}

func (_c *Store_DoVerifyCaller_Call) Run(run func(_a0 *model.Workspace, _a1 string)) *Store_DoVerifyCaller_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Workspace), args[1].(string))
	})
	return _c
}

func (_c *Store_DoVerifyCaller_Call) Return(_a0 bool, _a1 error) *Store_DoVerifyCaller_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_DoVerifyCaller_Call) RunAndReturn(run func(*model.Workspace, string) (bool, error)) *Store_DoVerifyCaller_Call {
	_c.Call.Return(run)
	return _c
}

// FinishValidation provides a mock function with given fields: _a0, _a1
func (_m *Store) FinishValidation(_a0 string, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_FinishValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishValidation'
type Store_FinishValidation_Call struct {
	*mock.Call
}

// FinishValidation is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) FinishValidation(_a0 interface{}, _a1 interface{}) *Store_FinishValidation_Call {
	return &Store_FinishValidation_Call{Call: _e.mock.On("FinishValidation", _a0, _a1)}
}

func (_c *Store_FinishValidation_Call) Run(run func(_a0 string, _a1 string)) *Store_FinishValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_FinishValidation_Call) Return(_a0 bool, _a1 error) *Store_FinishValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_FinishValidation_Call) RunAndReturn(run func(string, string) (bool, error)) *Store_FinishValidation_Call {
	_c.Call.Return(run)
	return _c
}

// GetBYODIDNumberData provides a mock function with given fields: _a0
func (_m *Store) GetBYODIDNumberData(_a0 string) (*model.WorkspaceDIDInfo, sql.NullString, error) {
	ret := _m.Called(_a0)

	var r0 *model.WorkspaceDIDInfo
	var r1 sql.NullString
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*model.WorkspaceDIDInfo, sql.NullString, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *model.WorkspaceDIDInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkspaceDIDInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) sql.NullString); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(sql.NullString)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_GetBYODIDNumberData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBYODIDNumberData'
type Store_GetBYODIDNumberData_Call struct {
	*mock.Call
}

// GetBYODIDNumberData is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) GetBYODIDNumberData(_a0 interface{}) *Store_GetBYODIDNumberData_Call {
	return &Store_GetBYODIDNumberData_Call{Call: _e.mock.On("GetBYODIDNumberData", _a0)}
}

func (_c *Store_GetBYODIDNumberData_Call) Run(run func(_a0 string)) *Store_GetBYODIDNumberData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetBYODIDNumberData_Call) Return(_a0 *model.WorkspaceDIDInfo, _a1 sql.NullString, _a2 error) *Store_GetBYODIDNumberData_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Store_GetBYODIDNumberData_Call) RunAndReturn(run func(string) (*model.WorkspaceDIDInfo, sql.NullString, error)) *Store_GetBYODIDNumberData_Call {
	_c.Call.Return(run)
	return _c
}

// GetBYOPSTNProvider provides a mock function with given fields: _a0, _a1, _a2
func (_m *Store) GetBYOPSTNProvider(_a0 string, _a1 string, _a2 int) (*model.PSTNInfo, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *model.PSTNInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int) (*model.PSTNInfo, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, int) *model.PSTNInfo); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PSTNInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetBYOPSTNProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBYOPSTNProvider'
type Store_GetBYOPSTNProvider_Call struct {
	*mock.Call
}

// GetBYOPSTNProvider is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
//   - _a2 int
func (_e *Store_Expecter) GetBYOPSTNProvider(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Store_GetBYOPSTNProvider_Call {
	return &Store_GetBYOPSTNProvider_Call{Call: _e.mock.On("GetBYOPSTNProvider", _a0, _a1, _a2)}
}

func (_c *Store_GetBYOPSTNProvider_Call) Run(run func(_a0 string, _a1 string, _a2 int)) *Store_GetBYOPSTNProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *Store_GetBYOPSTNProvider_Call) Return(_a0 *model.PSTNInfo, _a1 error) *Store_GetBYOPSTNProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetBYOPSTNProvider_Call) RunAndReturn(run func(string, string, int) (*model.PSTNInfo, error)) *Store_GetBYOPSTNProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetBestPSTNProvider provides a mock function with given fields: _a0, _a1
func (_m *Store) GetBestPSTNProvider(_a0 string, _a1 string) (*model.PSTNInfo, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.PSTNInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.PSTNInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.PSTNInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PSTNInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetBestPSTNProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBestPSTNProvider'
type Store_GetBestPSTNProvider_Call struct {
	*mock.Call
}

// GetBestPSTNProvider is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) GetBestPSTNProvider(_a0 interface{}, _a1 interface{}) *Store_GetBestPSTNProvider_Call {
	return &Store_GetBestPSTNProvider_Call{Call: _e.mock.On("GetBestPSTNProvider", _a0, _a1)}
}

func (_c *Store_GetBestPSTNProvider_Call) Run(run func(_a0 string, _a1 string)) *Store_GetBestPSTNProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_GetBestPSTNProvider_Call) Return(_a0 *model.PSTNInfo, _a1 error) *Store_GetBestPSTNProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetBestPSTNProvider_Call) RunAndReturn(run func(string, string) (*model.PSTNInfo, error)) *Store_GetBestPSTNProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetCallerIdToUse provides a mock function with given fields: _a0, _a1
func (_m *Store) GetCallerIdToUse(_a0 *model.Workspace, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Workspace, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*model.Workspace, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*model.Workspace, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetCallerIdToUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCallerIdToUse'
type Store_GetCallerIdToUse_Call struct {
	*mock.Call
}

// GetCallerIdToUse is a helper method to define mock.On call
//   - _a0 *model.Workspace
//   - _a1 string
func (_e *Store_Expecter) GetCallerIdToUse(_a0 interface{}, _a1 interface{}) *Store_GetCallerIdToUse_Call {
	return &Store_GetCallerIdToUse_Call{Call: _e.mock.On("GetCallerIdToUse", _a0, _a1)}
}

func (_c *Store_GetCallerIdToUse_Call) Run(run func(_a0 *model.Workspace, _a1 string)) *Store_GetCallerIdToUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Workspace), args[1].(string))
	})
	return _c
}

func (_c *Store_GetCallerIdToUse_Call) Return(_a0 string, _a1 error) *Store_GetCallerIdToUse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetCallerIdToUse_Call) RunAndReturn(run func(*model.Workspace, string) (string, error)) *Store_GetCallerIdToUse_Call {
	_c.Call.Return(run)
	return _c
}

// GetCodeFlowInfo provides a mock function with given fields: _a0, _a1
func (_m *Store) GetCodeFlowInfo(_a0 string, _a1 string) (*model.CodeFlowInfo, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.CodeFlowInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.CodeFlowInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.CodeFlowInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CodeFlowInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetCodeFlowInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCodeFlowInfo'
type Store_GetCodeFlowInfo_Call struct {
	*mock.Call
}

// GetCodeFlowInfo is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) GetCodeFlowInfo(_a0 interface{}, _a1 interface{}) *Store_GetCodeFlowInfo_Call {
	return &Store_GetCodeFlowInfo_Call{Call: _e.mock.On("GetCodeFlowInfo", _a0, _a1)}
}

func (_c *Store_GetCodeFlowInfo_Call) Run(run func(_a0 string, _a1 string)) *Store_GetCodeFlowInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_GetCodeFlowInfo_Call) Return(_a0 *model.CodeFlowInfo, _a1 error) *Store_GetCodeFlowInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetCodeFlowInfo_Call) RunAndReturn(run func(string, string) (*model.CodeFlowInfo, error)) *Store_GetCodeFlowInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetDIDAcceptOption provides a mock function with given fields: _a0
func (_m *Store) GetDIDAcceptOption(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetDIDAcceptOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDIDAcceptOption'
type Store_GetDIDAcceptOption_Call struct {
	*mock.Call
}

// GetDIDAcceptOption is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) GetDIDAcceptOption(_a0 interface{}) *Store_GetDIDAcceptOption_Call {
	return &Store_GetDIDAcceptOption_Call{Call: _e.mock.On("GetDIDAcceptOption", _a0)}
}

func (_c *Store_GetDIDAcceptOption_Call) Run(run func(_a0 string)) *Store_GetDIDAcceptOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetDIDAcceptOption_Call) Return(_a0 []byte, _a1 error) *Store_GetDIDAcceptOption_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetDIDAcceptOption_Call) RunAndReturn(run func(string) ([]byte, error)) *Store_GetDIDAcceptOption_Call {
	_c.Call.Return(run)
	return _c
}

// GetDIDNumberData provides a mock function with given fields: _a0
func (_m *Store) GetDIDNumberData(_a0 string) (*model.WorkspaceDIDInfo, sql.NullString, error) {
	ret := _m.Called(_a0)

	var r0 *model.WorkspaceDIDInfo
	var r1 sql.NullString
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*model.WorkspaceDIDInfo, sql.NullString, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *model.WorkspaceDIDInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WorkspaceDIDInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) sql.NullString); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(sql.NullString)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_GetDIDNumberData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDIDNumberData'
type Store_GetDIDNumberData_Call struct {
	*mock.Call
}

// GetDIDNumberData is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) GetDIDNumberData(_a0 interface{}) *Store_GetDIDNumberData_Call {
	return &Store_GetDIDNumberData_Call{Call: _e.mock.On("GetDIDNumberData", _a0)}
}

func (_c *Store_GetDIDNumberData_Call) Run(run func(_a0 string)) *Store_GetDIDNumberData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetDIDNumberData_Call) Return(_a0 *model.WorkspaceDIDInfo, _a1 sql.NullString, _a2 error) *Store_GetDIDNumberData_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Store_GetDIDNumberData_Call) RunAndReturn(run func(string) (*model.WorkspaceDIDInfo, sql.NullString, error)) *Store_GetDIDNumberData_Call {
	_c.Call.Return(run)
	return _c
}

// GetExtensionFlowInfo provides a mock function with given fields: _a0, _a1
func (_m *Store) GetExtensionFlowInfo(_a0 string, _a1 string) (*model.ExtensionFlowInfo, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.ExtensionFlowInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.ExtensionFlowInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.ExtensionFlowInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExtensionFlowInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetExtensionFlowInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtensionFlowInfo'
type Store_GetExtensionFlowInfo_Call struct {
	*mock.Call
}

// GetExtensionFlowInfo is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) GetExtensionFlowInfo(_a0 interface{}, _a1 interface{}) *Store_GetExtensionFlowInfo_Call {
	return &Store_GetExtensionFlowInfo_Call{Call: _e.mock.On("GetExtensionFlowInfo", _a0, _a1)}
}

func (_c *Store_GetExtensionFlowInfo_Call) Run(run func(_a0 string, _a1 string)) *Store_GetExtensionFlowInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_GetExtensionFlowInfo_Call) Return(_a0 *model.ExtensionFlowInfo, _a1 error) *Store_GetExtensionFlowInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetExtensionFlowInfo_Call) RunAndReturn(run func(string, string) (*model.ExtensionFlowInfo, error)) *Store_GetExtensionFlowInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowInfo provides a mock function with given fields: _a0, _a1
func (_m *Store) GetFlowInfo(_a0 string, _a1 string) (*model.ExtensionFlowInfo, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.ExtensionFlowInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.ExtensionFlowInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.ExtensionFlowInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ExtensionFlowInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetFlowInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowInfo'
type Store_GetFlowInfo_Call struct {
	*mock.Call
}

// GetFlowInfo is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) GetFlowInfo(_a0 interface{}, _a1 interface{}) *Store_GetFlowInfo_Call {
	return &Store_GetFlowInfo_Call{Call: _e.mock.On("GetFlowInfo", _a0, _a1)}
}

func (_c *Store_GetFlowInfo_Call) Run(run func(_a0 string, _a1 string)) *Store_GetFlowInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_GetFlowInfo_Call) Return(_a0 *model.ExtensionFlowInfo, _a1 error) *Store_GetFlowInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetFlowInfo_Call) RunAndReturn(run func(string, string) (*model.ExtensionFlowInfo, error)) *Store_GetFlowInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettings provides a mock function with given fields:
func (_m *Store) GetSettings() (*model.Settings, error) {
	ret := _m.Called()

	var r0 *model.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Settings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Settings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Settings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type Store_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
func (_e *Store_Expecter) GetSettings() *Store_GetSettings_Call {
	return &Store_GetSettings_Call{Call: _e.mock.On("GetSettings")}
}

func (_c *Store_GetSettings_Call) Run(run func()) *Store_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_GetSettings_Call) Return(_a0 *model.Settings, _a1 error) *Store_GetSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetSettings_Call) RunAndReturn(run func() (*model.Settings, error)) *Store_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByDID provides a mock function with given fields: did
func (_m *Store) GetUserByDID(did string) (string, error) {
	ret := _m.Called(did)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(did)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(did)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(did)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserByDID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByDID'
type Store_GetUserByDID_Call struct {
	*mock.Call
}

// GetUserByDID is a helper method to define mock.On call
//   - did string
func (_e *Store_Expecter) GetUserByDID(did interface{}) *Store_GetUserByDID_Call {
	return &Store_GetUserByDID_Call{Call: _e.mock.On("GetUserByDID", did)}
}

func (_c *Store_GetUserByDID_Call) Run(run func(did string)) *Store_GetUserByDID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetUserByDID_Call) Return(_a0 string, _a1 error) *Store_GetUserByDID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserByDID_Call) RunAndReturn(run func(string) (string, error)) *Store_GetUserByDID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByTrunkSourceIp provides a mock function with given fields: _a0
func (_m *Store) GetUserByTrunkSourceIp(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserByTrunkSourceIp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByTrunkSourceIp'
type Store_GetUserByTrunkSourceIp_Call struct {
	*mock.Call
}

// GetUserByTrunkSourceIp is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) GetUserByTrunkSourceIp(_a0 interface{}) *Store_GetUserByTrunkSourceIp_Call {
	return &Store_GetUserByTrunkSourceIp_Call{Call: _e.mock.On("GetUserByTrunkSourceIp", _a0)}
}

func (_c *Store_GetUserByTrunkSourceIp_Call) Run(run func(_a0 string)) *Store_GetUserByTrunkSourceIp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetUserByTrunkSourceIp_Call) Return(_a0 string, _a1 error) *Store_GetUserByTrunkSourceIp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserByTrunkSourceIp_Call) RunAndReturn(run func(string) (string, error)) *Store_GetUserByTrunkSourceIp_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoutedServer2 provides a mock function with given fields: _a0, _a1, _a2
func (_m *Store) GetUserRoutedServer2(_a0 bool, _a1 *model.Workspace, _a2 string) (*lineblocs.MediaServer, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *lineblocs.MediaServer
	var r1 error
	if rf, ok := ret.Get(0).(func(bool, *model.Workspace, string) (*lineblocs.MediaServer, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(bool, *model.Workspace, string) *lineblocs.MediaServer); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lineblocs.MediaServer)
		}
	}

	if rf, ok := ret.Get(1).(func(bool, *model.Workspace, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetUserRoutedServer2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoutedServer2'
type Store_GetUserRoutedServer2_Call struct {
	*mock.Call
}

// GetUserRoutedServer2 is a helper method to define mock.On call
//   - _a0 bool
//   - _a1 *model.Workspace
//   - _a2 string
func (_e *Store_Expecter) GetUserRoutedServer2(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Store_GetUserRoutedServer2_Call {
	return &Store_GetUserRoutedServer2_Call{Call: _e.mock.On("GetUserRoutedServer2", _a0, _a1, _a2)}
}

func (_c *Store_GetUserRoutedServer2_Call) Run(run func(_a0 bool, _a1 *model.Workspace, _a2 string)) *Store_GetUserRoutedServer2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(*model.Workspace), args[2].(string))
	})
	return _c
}

func (_c *Store_GetUserRoutedServer2_Call) Return(_a0 *lineblocs.MediaServer, _a1 error) *Store_GetUserRoutedServer2_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetUserRoutedServer2_Call) RunAndReturn(run func(bool, *model.Workspace, string) (*lineblocs.MediaServer, error)) *Store_GetUserRoutedServer2_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspaceMacros provides a mock function with given fields: _a0
func (_m *Store) GetWorkspaceMacros(_a0 string) ([]model.MacroFunction, error) {
	ret := _m.Called(_a0)

	var r0 []model.MacroFunction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]model.MacroFunction, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []model.MacroFunction); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MacroFunction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetWorkspaceMacros_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspaceMacros'
type Store_GetWorkspaceMacros_Call struct {
	*mock.Call
}

// GetWorkspaceMacros is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) GetWorkspaceMacros(_a0 interface{}) *Store_GetWorkspaceMacros_Call {
	return &Store_GetWorkspaceMacros_Call{Call: _e.mock.On("GetWorkspaceMacros", _a0)}
}

func (_c *Store_GetWorkspaceMacros_Call) Run(run func(_a0 string)) *Store_GetWorkspaceMacros_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_GetWorkspaceMacros_Call) Return(_a0 []model.MacroFunction, _a1 error) *Store_GetWorkspaceMacros_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetWorkspaceMacros_Call) RunAndReturn(run func(string) ([]model.MacroFunction, error)) *Store_GetWorkspaceMacros_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspaceParams provides a mock function with given fields: _a0
func (_m *Store) GetWorkspaceParams(_a0 int) (*[]model.WorkspaceParam, error) {
	ret := _m.Called(_a0)

	var r0 *[]model.WorkspaceParam
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*[]model.WorkspaceParam, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) *[]model.WorkspaceParam); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.WorkspaceParam)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_GetWorkspaceParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspaceParams'
type Store_GetWorkspaceParams_Call struct {
	*mock.Call
}

// GetWorkspaceParams is a helper method to define mock.On call
//   - _a0 int
func (_e *Store_Expecter) GetWorkspaceParams(_a0 interface{}) *Store_GetWorkspaceParams_Call {
	return &Store_GetWorkspaceParams_Call{Call: _e.mock.On("GetWorkspaceParams", _a0)}
}

func (_c *Store_GetWorkspaceParams_Call) Run(run func(_a0 int)) *Store_GetWorkspaceParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Store_GetWorkspaceParams_Call) Return(_a0 *[]model.WorkspaceParam, _a1 error) *Store_GetWorkspaceParams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_GetWorkspaceParams_Call) RunAndReturn(run func(int) (*[]model.WorkspaceParam, error)) *Store_GetWorkspaceParams_Call {
	_c.Call.Return(run)
	return _c
}

// HostedSIPTrunkLookup provides a mock function with given fields: _a0, _a1
func (_m *Store) HostedSIPTrunkLookup(_a0 string, _a1 *model.Workspace) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.Workspace) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *model.Workspace) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *model.Workspace) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_HostedSIPTrunkLookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HostedSIPTrunkLookup'
type Store_HostedSIPTrunkLookup_Call struct {
	*mock.Call
}

// HostedSIPTrunkLookup is a helper method to define mock.On call
//   - _a0 string
//   - _a1 *model.Workspace
func (_e *Store_Expecter) HostedSIPTrunkLookup(_a0 interface{}, _a1 interface{}) *Store_HostedSIPTrunkLookup_Call {
	return &Store_HostedSIPTrunkLookup_Call{Call: _e.mock.On("HostedSIPTrunkLookup", _a0, _a1)}
}

func (_c *Store_HostedSIPTrunkLookup_Call) Run(run func(_a0 string, _a1 *model.Workspace)) *Store_HostedSIPTrunkLookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.Workspace))
	})
	return _c
}

func (_c *Store_HostedSIPTrunkLookup_Call) Return(_a0 bool, _a1 error) *Store_HostedSIPTrunkLookup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_HostedSIPTrunkLookup_Call) RunAndReturn(run func(string, *model.Workspace) (bool, error)) *Store_HostedSIPTrunkLookup_Call {
	_c.Call.Return(run)
	return _c
}

// IPWhitelistLookup provides a mock function with given fields: _a0, _a1
func (_m *Store) IPWhitelistLookup(_a0 string, _a1 *model.Workspace) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *model.Workspace) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *model.Workspace) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *model.Workspace) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IPWhitelistLookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPWhitelistLookup'
type Store_IPWhitelistLookup_Call struct {
	*mock.Call
}

// IPWhitelistLookup is a helper method to define mock.On call
//   - _a0 string
//   - _a1 *model.Workspace
func (_e *Store_Expecter) IPWhitelistLookup(_a0 interface{}, _a1 interface{}) *Store_IPWhitelistLookup_Call {
	return &Store_IPWhitelistLookup_Call{Call: _e.mock.On("IPWhitelistLookup", _a0, _a1)}
}

func (_c *Store_IPWhitelistLookup_Call) Run(run func(_a0 string, _a1 *model.Workspace)) *Store_IPWhitelistLookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*model.Workspace))
	})
	return _c
}

func (_c *Store_IPWhitelistLookup_Call) Return(_a0 bool, _a1 error) *Store_IPWhitelistLookup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IPWhitelistLookup_Call) RunAndReturn(run func(string, *model.Workspace) (bool, error)) *Store_IPWhitelistLookup_Call {
	_c.Call.Return(run)
	return _c
}

// IncomingBYODIDValidation provides a mock function with given fields: _a0
func (_m *Store) IncomingBYODIDValidation(_a0 string) (*model.DidNumberInfo, error) {
	ret := _m.Called(_a0)

	var r0 *model.DidNumberInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.DidNumberInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *model.DidNumberInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DidNumberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IncomingBYODIDValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncomingBYODIDValidation'
type Store_IncomingBYODIDValidation_Call struct {
	*mock.Call
}

// IncomingBYODIDValidation is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) IncomingBYODIDValidation(_a0 interface{}) *Store_IncomingBYODIDValidation_Call {
	return &Store_IncomingBYODIDValidation_Call{Call: _e.mock.On("IncomingBYODIDValidation", _a0)}
}

func (_c *Store_IncomingBYODIDValidation_Call) Run(run func(_a0 string)) *Store_IncomingBYODIDValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_IncomingBYODIDValidation_Call) Return(_a0 *model.DidNumberInfo, _a1 error) *Store_IncomingBYODIDValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IncomingBYODIDValidation_Call) RunAndReturn(run func(string) (*model.DidNumberInfo, error)) *Store_IncomingBYODIDValidation_Call {
	_c.Call.Return(run)
	return _c
}

// IncomingDIDValidation provides a mock function with given fields: _a0
func (_m *Store) IncomingDIDValidation(_a0 string) (*model.DidNumberInfo, error) {
	ret := _m.Called(_a0)

	var r0 *model.DidNumberInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.DidNumberInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *model.DidNumberInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DidNumberInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IncomingDIDValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncomingDIDValidation'
type Store_IncomingDIDValidation_Call struct {
	*mock.Call
}

// IncomingDIDValidation is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) IncomingDIDValidation(_a0 interface{}) *Store_IncomingDIDValidation_Call {
	return &Store_IncomingDIDValidation_Call{Call: _e.mock.On("IncomingDIDValidation", _a0)}
}

func (_c *Store_IncomingDIDValidation_Call) Run(run func(_a0 string)) *Store_IncomingDIDValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_IncomingDIDValidation_Call) Return(_a0 *model.DidNumberInfo, _a1 error) *Store_IncomingDIDValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IncomingDIDValidation_Call) RunAndReturn(run func(string) (*model.DidNumberInfo, error)) *Store_IncomingDIDValidation_Call {
	_c.Call.Return(run)
	return _c
}

// IncomingMediaServerValidation provides a mock function with given fields: _a0
func (_m *Store) IncomingMediaServerValidation(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IncomingMediaServerValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncomingMediaServerValidation'
type Store_IncomingMediaServerValidation_Call struct {
	*mock.Call
}

// IncomingMediaServerValidation is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) IncomingMediaServerValidation(_a0 interface{}) *Store_IncomingMediaServerValidation_Call {
	return &Store_IncomingMediaServerValidation_Call{Call: _e.mock.On("IncomingMediaServerValidation", _a0)}
}

func (_c *Store_IncomingMediaServerValidation_Call) Run(run func(_a0 string)) *Store_IncomingMediaServerValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_IncomingMediaServerValidation_Call) Return(_a0 bool, _a1 error) *Store_IncomingMediaServerValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IncomingMediaServerValidation_Call) RunAndReturn(run func(string) (bool, error)) *Store_IncomingMediaServerValidation_Call {
	_c.Call.Return(run)
	return _c
}

// IncomingTrunkValidation provides a mock function with given fields: _a0
func (_m *Store) IncomingTrunkValidation(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_IncomingTrunkValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncomingTrunkValidation'
type Store_IncomingTrunkValidation_Call struct {
	*mock.Call
}

// IncomingTrunkValidation is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) IncomingTrunkValidation(_a0 interface{}) *Store_IncomingTrunkValidation_Call {
	return &Store_IncomingTrunkValidation_Call{Call: _e.mock.On("IncomingTrunkValidation", _a0)}
}

func (_c *Store_IncomingTrunkValidation_Call) Run(run func(_a0 string)) *Store_IncomingTrunkValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_IncomingTrunkValidation_Call) Return(_a0 []byte, _a1 error) *Store_IncomingTrunkValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_IncomingTrunkValidation_Call) RunAndReturn(run func(string) ([]byte, error)) *Store_IncomingTrunkValidation_Call {
	_c.Call.Return(run)
	return _c
}

// LogCallByeEvent provides a mock function with given fields: _a0
func (_m *Store) LogCallByeEvent(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_LogCallByeEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogCallByeEvent'
type Store_LogCallByeEvent_Call struct {
	*mock.Call
}

// LogCallByeEvent is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) LogCallByeEvent(_a0 interface{}) *Store_LogCallByeEvent_Call {
	return &Store_LogCallByeEvent_Call{Call: _e.mock.On("LogCallByeEvent", _a0)}
}

func (_c *Store_LogCallByeEvent_Call) Run(run func(_a0 string)) *Store_LogCallByeEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_LogCallByeEvent_Call) Return(_a0 error) *Store_LogCallByeEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_LogCallByeEvent_Call) RunAndReturn(run func(string) error) *Store_LogCallByeEvent_Call {
	_c.Call.Return(run)
	return _c
}

// LogCallInviteEvent provides a mock function with given fields: _a0
func (_m *Store) LogCallInviteEvent(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_LogCallInviteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogCallInviteEvent'
type Store_LogCallInviteEvent_Call struct {
	*mock.Call
}

// LogCallInviteEvent is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) LogCallInviteEvent(_a0 interface{}) *Store_LogCallInviteEvent_Call {
	return &Store_LogCallInviteEvent_Call{Call: _e.mock.On("LogCallInviteEvent", _a0)}
}

func (_c *Store_LogCallInviteEvent_Call) Run(run func(_a0 string)) *Store_LogCallInviteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_LogCallInviteEvent_Call) Return(_a0 error) *Store_LogCallInviteEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_LogCallInviteEvent_Call) RunAndReturn(run func(string) error) *Store_LogCallInviteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// LookupSIPTrunkByDID provides a mock function with given fields: _a0
func (_m *Store) LookupSIPTrunkByDID(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_LookupSIPTrunkByDID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupSIPTrunkByDID'
type Store_LookupSIPTrunkByDID_Call struct {
	*mock.Call
}

// LookupSIPTrunkByDID is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) LookupSIPTrunkByDID(_a0 interface{}) *Store_LookupSIPTrunkByDID_Call {
	return &Store_LookupSIPTrunkByDID_Call{Call: _e.mock.On("LookupSIPTrunkByDID", _a0)}
}

func (_c *Store_LookupSIPTrunkByDID_Call) Run(run func(_a0 string)) *Store_LookupSIPTrunkByDID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_LookupSIPTrunkByDID_Call) Return(_a0 []byte, _a1 error) *Store_LookupSIPTrunkByDID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_LookupSIPTrunkByDID_Call) RunAndReturn(run func(string) ([]byte, error)) *Store_LookupSIPTrunkByDID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessDialplan provides a mock function with given fields: _a0
func (_m *Store) ProcessDialplan(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ProcessDialplan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessDialplan'
type Store_ProcessDialplan_Call struct {
	*mock.Call
}

// ProcessDialplan is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) ProcessDialplan(_a0 interface{}) *Store_ProcessDialplan_Call {
	return &Store_ProcessDialplan_Call{Call: _e.mock.On("ProcessDialplan", _a0)}
}

func (_c *Store_ProcessDialplan_Call) Run(run func(_a0 string)) *Store_ProcessDialplan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_ProcessDialplan_Call) Return(_a0 []byte, _a1 error) *Store_ProcessDialplan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ProcessDialplan_Call) RunAndReturn(run func(string) ([]byte, error)) *Store_ProcessDialplan_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessSIPTrunkCall provides a mock function with given fields: _a0
func (_m *Store) ProcessSIPTrunkCall(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ProcessSIPTrunkCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessSIPTrunkCall'
type Store_ProcessSIPTrunkCall_Call struct {
	*mock.Call
}

// ProcessSIPTrunkCall is a helper method to define mock.On call
//   - _a0 string
func (_e *Store_Expecter) ProcessSIPTrunkCall(_a0 interface{}) *Store_ProcessSIPTrunkCall_Call {
	return &Store_ProcessSIPTrunkCall_Call{Call: _e.mock.On("ProcessSIPTrunkCall", _a0)}
}

func (_c *Store_ProcessSIPTrunkCall_Call) Run(run func(_a0 string)) *Store_ProcessSIPTrunkCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Store_ProcessSIPTrunkCall_Call) Return(_a0 []byte, _a1 error) *Store_ProcessSIPTrunkCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ProcessSIPTrunkCall_Call) RunAndReturn(run func(string) ([]byte, error)) *Store_ProcessSIPTrunkCall_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRegistration provides a mock function with given fields: _a0, _a1, _a2
func (_m *Store) StoreRegistration(_a0 string, _a1 int, _a2 *model.Workspace) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, *model.Workspace) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_StoreRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRegistration'
type Store_StoreRegistration_Call struct {
	*mock.Call
}

// StoreRegistration is a helper method to define mock.On call
//   - _a0 string
//   - _a1 int
//   - _a2 *model.Workspace
func (_e *Store_Expecter) StoreRegistration(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Store_StoreRegistration_Call {
	return &Store_StoreRegistration_Call{Call: _e.mock.On("StoreRegistration", _a0, _a1, _a2)}
}

func (_c *Store_StoreRegistration_Call) Run(run func(_a0 string, _a1 int, _a2 *model.Workspace)) *Store_StoreRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(*model.Workspace))
	})
	return _c
}

func (_c *Store_StoreRegistration_Call) Return(_a0 error) *Store_StoreRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_StoreRegistration_Call) RunAndReturn(run func(string, int, *model.Workspace) error) *Store_StoreRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccess provides a mock function with given fields: _a0, _a1
func (_m *Store) ValidateAccess(_a0 string, _a1 string) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Store_ValidateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccess'
type Store_ValidateAccess_Call struct {
	*mock.Call
}

// ValidateAccess is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *Store_Expecter) ValidateAccess(_a0 interface{}, _a1 interface{}) *Store_ValidateAccess_Call {
	return &Store_ValidateAccess_Call{Call: _e.mock.On("ValidateAccess", _a0, _a1)}
}

func (_c *Store_ValidateAccess_Call) Run(run func(_a0 string, _a1 string)) *Store_ValidateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Store_ValidateAccess_Call) Return(_a0 bool) *Store_ValidateAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_ValidateAccess_Call) RunAndReturn(run func(string, string) bool) *Store_ValidateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
